DROP TABLE IF EXISTS status;

DROP TABLE IF EXISTS metric;

DROP TABLE IF EXISTS bigquery_job;

DROP TABLE IF EXISTS audit_result;

DROP TABLE IF EXISTS audit;

DROP TABLE IF EXISTS profile;

DROP TABLE IF EXISTS entity;
