{
 "title": "Predator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "environment", "query": { "query": "label_values(environment)" } },
   { "name": "entity", "query": { "query": "label_values(entity)" } },
   { "name": "adhoc", "label": "adhoc query" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Predator Spec Count",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predator_spec_count_value{deployment=\"$deployment\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Predator Profile Job Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(predator_profile_job_failed_count_value{deployment=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Predator Audit Job Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(predator_profile_audit_failed_count_value{deployment=\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Predator Bigquery Job Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predator_profile_bigquery_job_failed_count_value{deployment=\"$deployment\"}"
    }
   ]
  },
  {
   "title": "Profile Job Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entity) (predator_profile_job_created_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})",
     "legendFormat": "{{entity}}_created"
    },
    {
     "expr": "sum by (entity) (predator_profile_job_completed_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})",
     "legendFormat": "{{entity}}_completed"
    },
    {
     "expr": "sum by (entity)(predator_profile_job_failed_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})",
     "legendFormat": "{{entity}}_failed"
    }
   ]
  },
  {
   "title": "Audit Job Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entity) (predator_audit_job_created_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})",
     "legendFormat": "{{entity}}_created"
    },
    {
     "expr": "sum by (entity)(predator_audit_job_completed_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})",
     "legendFormat": "{{entity}}_completed"
    },
    {
     "expr": "sum by (entity)(predator_audit_job_failed_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "Bigquery Job Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entity) (predator_profile_bigquery_job_created_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Total Data Processed Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (entity) (predator_profile_bigquery_job_totalbytes_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"})",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  { "title": "Spec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Predator Spec Activity $entity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predator_spec_added_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"}",
     "legendFormat": "added"
    },
    {
     "expr": "predator_spec_removed_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"}",
     "legendFormat": "deleted"
    },
    {
     "expr": "predator_spec_updated_count_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"}",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Predator Upload Job Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "predator_spec_upload_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Profile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profile Job Time $entity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "quantile(0.99,predator_profile_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "90th percentile"
      },
      {
       "expr": "quantile(0.9,predator_profile_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "90th percentile"
      },
      {
       "expr": "quantile(0.75,predator_profile_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "75th percentile"
      },
      {
       "expr": "avg(predator_profile_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit Job time $entity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "quantile(0.99,predator_audit_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "99th percentile"
      },
      {
       "expr": "quantile(0.90,predator_audit_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "90th percentile"
      },
      {
       "expr": "quantile(0.75,predator_audit_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "90th percentile"
      },
      {
       "expr": "avg(predator_audit_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Bigquery Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bigquery Job Time $entity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (project,dataset,table) (predator_profile_bigquery_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}"
      }
     ]
    },
    {
     "title": "Bigquery Job Time $entity breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "predator_profile_bigquery_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"metadata\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      },
      {
       "expr": "predator_profile_bigquery_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"column_metric\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      },
      {
       "expr": "predator_profile_bigquery_job_time_100_percentile{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"table_metric\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      }
     ]
    },
    {
     "title": "Total Data Processed Bytes $entity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (project,dataset,table) (predator_profile_bigquery_job_totalbytes_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}"
      }
     ]
    },
    {
     "title": "Total Data Processed Bytes $entity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "predator_profile_bigquery_job_totalbytes_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"metadata\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      },
      {
       "expr": "predator_profile_bigquery_job_totalbytes_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"column_metric\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      },
      {
       "expr": "predator_profile_bigquery_job_totalbytes_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"table_metric\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      }
     ]
    },
    {
     "title": "Bigquery Slot Millis $entity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (project,dataset,table) (predator_profile_bigquery_job_slotmillis_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\"})",
       "legendFormat": "{{project}}.{{dataset}}.{{table}} "
      }
     ]
    },
    {
     "title": "Bigquery Slot Millis $entity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "predator_profile_bigquery_job_slotmillis_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"metadata\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      },
      {
       "expr": "predator_profile_bigquery_job_slotmillis_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"table_metric\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      },
      {
       "expr": "predator_profile_bigquery_job_slotmillis_value{deployment=~\"$deployment\",pod=~\"$pod\",environment=~\"$environment\",entity=~\"$entity\",query_type=~\"column_metric\"}",
       "legendFormat": "{{project}}.{{dataset}}.{{table}}:{{query_type}}"
      }
     ]
    }
   ]
  }
 ]
}