name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  publish-latest:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push latest predator image
        run: env GOOS=linux GOARCH=amd64 make build && docker build -t docker.io/odpf/predator:latest . && docker push docker.io/odpf/predator:latest
